---
name: "FrameDropCheck.Plugin"
guid: "d3075c1e-6e7c-4a70-b989-170aa2f4aa3e"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "linetor"
artifacts:
  - "FrameDropCheck.Plugin.dll"
changelog: >
  changelog
