name: '🏗️ Build Plugin'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    with:
      dotnet-version: 9.0.x
      dotnet-target: net9.0
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@master
