# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@8c80ef19722c31ac9d6eac77b8cd291f9ff8d429 # master
    secrets:
      token: .
