# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@c971ac64507ae87f30632770506c204b55b13ff4 # master
    secrets:
      token: .
