name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@fdc7da9b15f696978f5973c1616c8bc663c677e8 # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
