name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@8c80ef19722c31ac9d6eac77b8cd291f9ff8d429 # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
