name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@601009caac9d7e9f891ef8ed8bb9446490b7c1c1 # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
